services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: sft_pgvector
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "Sonu@12345"
      POSTGRES_DB: sft_vector_db
    ports:
      - "5433:5432"
    volumes:
      - pgvector_data:/var/lib/postgresql/data

volumes:
  pgvector_data: